<div class="web-monetization">
    <div class="web-monetization-start">
        <span class="control-text"><?php echo $this->siteSetting('web_monetization_message_site_disabled') ?? $this->translate(\WebMonetization\Module::MESSAGE_SITE_DISABLED); ?></span>
        <button class="web-monetization-start-button"><?php echo $this->translate('Start donating'); ?></button>
    </div>
    <div class="web-monetization-stop">
        <span class="control-text"><?php echo $this->siteSetting('web_monetization_message_site_enabled') ?? $this->translate(\WebMonetization\Module::MESSAGE_SITE_ENABLED); ?></span>
        <button class="web-monetization-stop-button"><?php echo $this->translate('Stop donating'); ?></button>
    </div>
    <div class="web-monetization-disabled">
        <span class="control-text"><?php echo $this->siteSetting('web_monetization_message_monetization_disabled') ?? $this->translate(\WebMonetization\Module::MESSAGE_MONETIZATION_DISABLED); ?></span>
    </div>
</div>
